[package]
name = "ap-pair-astro-xastro"
version = "1.0.1"
authors = ["Astroport"]
edition = "2021"
description = "Definition and types for the ASTRO-xASTRO pair interface"
license = "GPL-3.0-only"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
ap-pair = { path = "../pair" }
astroport = { path = "../astroport" }
cosmwasm-schema = "1.1"
cw20 = "0.15"
cosmwasm-std = "1.1"
