[package]
name = "classic-bindings"
version = "0.1.1"
authors = ["nghuyenthevinh2000 <nghuyenthevinh@gmail.com>"]
edition = "2021"
description = "Bindings for CustomMsg and CustomQuery for the Terra Classic blockchain"
repository = "https://github.com/classic-terra/terra-bindings"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = "1.1"
cosmwasm-std = "1.1"
schemars = "0.8"
serde = { version = "1.0", default-features = false, features = ["derive"] }

[dev-dependencies]
