[package]
name = "astroport-mocks"
version = "0.2.0"
authors = ["Astroport"]
edition = "2021"
description = "Mock Astroport contracts used for integration testing"
license = "GPL-3.0-only"
repository = "https://github.com/astroport-fi/astroport-core"
homepage = "https://astroport.fi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
astroport = { path = "../astroport" }
astroport-factory = { path = "../../contracts/factory" }
astroport-native-coin-registry = { path = "../../contracts/periphery/native_coin_registry" }
astroport-pair = { path = "../../contracts/pair" }
astroport-pair-stable = { path = "../../contracts/pair_stable" }
astroport-pair-concentrated = { path = "../../contracts/pair_concentrated" }
astroport-staking = { path = "../../contracts/tokenomics/staking" }
astroport-token = { path = "../../contracts/token" }
astroport-vesting = { path = "../../contracts/tokenomics/vesting" }
astroport-whitelist = { path = "../../contracts/whitelist" }
astroport-xastro-token = { path = "../../contracts/tokenomics/xastro_token" }
cosmwasm-schema = "1.2.5"
cosmwasm-std = "1.2.5"
multi-test = { package = "cw-multi-test", version = "0.20.0", features = ["cosmwasm_1_1"] }

injective-cosmwasm = "0.2"
schemars = "0.8.1"
serde = "1.0"
cw-utils = "1.0"
cw20 = "0.15"
anyhow = "1.0"
cw3 = "1.0"
